# {# pkglts, travis
# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
# #}

addons:
  apt:
    packages:
     - python-numpy
     - python-scipy
# {# pkglts, travis.addons

 #}

install:
 - pip install --upgrade git+https://github.com/openalea/deploy#egg=OpenAlea.Deploy
 - pip install --upgrade git+https://github.com/openalea/core
 - pip install --upgrade git+https://github.com/openalea/container
# {# pkglts, travis.install
 - pip install -r requirements.txt
 - pip install -r dvlpt_requirements.txt
# #}

script:
# {# pkglts, travis.script
 - nosetests
# #}

after_success:
# {# pkglts, travis.after

# #}
